### ISSUE TITLE
Message filter

### ISSUE THREAD

**Issue by ghost** [milan252525/LAcogs#52]
**Is your feature request related to a problem? Please describe.**
Even though we trust the mods in our servers and all, there's still the human factor, they can't be online 24/7, can't watch all chats 24/7, so it's far easier to make an automated system watch over chats and delete messages containing unwanted words. 

**Describe the solution you'd like**
Very simple. Make the bot watch all channels and delete the messages that contain blacklisted words. May be performance issues.

**Additional context**
The list of words that should be filtered has to be further discussed.

**Comment by milan252525** [comment]
The bot has word filter. filter cog > /filter

**Comment by ghost** [comment]
That's good, asked about a list of words, will setup them and close the issue.
